### ISSUE TITLE
fping latency and packet graphs are wrong

### ISSUE THREAD

**Issue by l2isbad** [firehol/netdata#1200]
On current version of netdata fping graphs looks like

![fping_netdata](https://cloud.githubusercontent.com/assets/22274335/19956159/64dc08a6-a1cc-11e6-9538-bbaad37d98ee.png)

But there is no packet drops or something because of all 5 echo replys are always back according "returned" graph and tcpdump. I double check it with /opt/netdata/usr/libexec/netdata/plugins.d./fping.plugin - output is always "SET xmt = 5 SET rcv = 5"

**Comment by ktsaou** [comment]
Yes I know.
It is an fping problem: https://github.com/schweikert/fping/pull/105#issuecomment-258005445

Let's way a bit for @schweikert to fix it.

**Comment by ktsaou** [comment]
oh, I see it is already fixed.
Please install the latest fping by running:

```sh
/usr/libexec/netdata/plugins.d/fping.plugin install
```

**Comment by l2isbad** [comment]
Hm..after installing a new version of the fping plugin the problem still on "packet" chart. And no problem on "latency"

**Comment by ktsaou** [comment]
Well... this is by fping design.

The patch in question was implemented to fix the quality chart. Before this patch the returned packets was varying below and above 100%. The reason is that a packet was sent and 0.999 sec and received at 1.001 sec, so the first second was reporting < 100% and the next > 100%.

@schweikert (the maintainer of fping) fixed that by discarding the packet that was received at 1.001 sec, so that the quality chart is stable at 100%.

This however introduced the problem you describe: the count of packets received is misleading.

I have already suggested that this patch will introduce more problems than the ones it solves, but it is up to @schweikert to decide that and implement it in fping the way he sees fit.

**Comment by l2isbad** [comment]
So if "packet" chart is broken why we need it? Result will be confusion and questions only i think

**Comment by schweikert** [comment]
Reporting packet loss is certainly worse than having sometimes less packets sent and received. Don't you agree? The typical way to show this data is latency and loss%.

**Comment by ktsaou** [comment]
> Reporting packet loss is certainly worse than having sometimes less packets sent and received. Don't you agree? The typical way to show this data is latency and loss%.

You are right! The way fping is now, this is probably the best solution.
