### ISSUE TITLE
Deleting orphan hosts cache not working

### ISSUE THREAD

**Issue by shellshock1953** [firehol/netdata#2329]
Hello,
We generate new netdata.public.unique.id every time VM starts (in AWS ASG). 
This one produces next issue: cache of slave-nodes on master-node is not cleaning.
There are options in global netdata configuration "delete orphan hosts files" and "delete obsolete charts files" however it's not working.

**Comment by ktsaou** [comment]
You are right.
It seems this functionality works currently only for proxies.
Making a PR now to fix it, so that it will work for masters too.

**Comment by ktsaou** [comment]
I fixed it.

**Comment by ktsaou** [comment]
It is in PR #2337 . Will be merged in a while.

**Comment by shellshock1953** [comment]
Updated netdata on master and all nodes (v602).
Wait more than a week, but cache is still not cleaning.

Config on master node:
```
[global]
 run as user = netdata
 web files owner = root
 web files group = netdata
 bind to = 0.0.0.0
 memory mode = ram
 history = 3600
 cache directory = /var/cache/netdata
 delete obsolete charts files = yes
 delete orphan hosts files = yes
 cleanup obsolete charts after seconds = 14400
 cleanup orphan hosts after seconds = 14400
```

**Comment by ktsaou** [comment]
Did you restart netdata in the mean time? If yes, it does not delete them (it is not aware of them).
There is already a request to cleanup or take various actions on charts found on disk but not used: #2292 

If you haven't restarted netdata, we may still have a bug...

**Comment by shellshock1953** [comment]
Have restarted netdata few times during last week.
Also, just to be sure - restarted it just now.
Still a have a lot of orphan cache.

**Comment by ktsaou** [comment]
Yes, this is the problem. When you restart netdata it "forgets" the files it should clean.
I can probably make it delete the orphan files when you stop netdata.
Let me check...

**Comment by ktsaou** [comment]
ok, I added the code to cleanup orphan hosts and obsolete charts on exit.
Can you test it? Install `https://github.com/ktsaou/netdata`.

With this change, when netdata exits, it deletes the files of orphan hosts (ie hosts that are not receiving any metrics) and obsolete charts (ie charts of a host that have been marked as obsolete - unmounted disks, removed network interfaces, etc).

**Comment by shellshock1953** [comment]
Ok, now its working.
Is it possible to do drop-cache without restart of central netdata?

**Comment by ktsaou** [comment]
It does it automatically when any host starts streaming metrics, and at least 1 hour has passed since the disconnection of the host. So, it should automatically cleanup. If 1 hour is too much for you, you can set it in netdata.conf, option `cleanup orphan hosts after seconds = 3600`.

The problem was that if you restarted netdata it was not cleaning up. Now it does.

**Comment by ktsaou** [comment]
merged the fix
