### ISSUE TITLE
Cannot load required JS library: http://ipaddress:19999/dashboard_info.js?v20180510-2 after update or fresh install

### ISSUE THREAD

**Issue by EgerUS** [firehol/netdata#3707]
Hello,
 today I install netdata on fresh server with Debian 9 and I get this error on loading web gui in browser (Chrome and Firefox).
Next I try to update working netdata on another Debian 9 server with same result after update.
I used one line installation with bash <(curl -Ss https://my-netdata.io/kickstart.sh)
Some bug in new version ?

**Comment by UavLabsColombia** [comment]
Hola a Todos, realice la actualizacion del netdata a la ultima version y me esta saltando el mismo error indicado por @EgerUS  
Cannot load required JS library: http://site.org:19999/dashboard_info.js?v20180510-2
En ubuntu ocurre el problema, sobre debian no me ha ocurrido. 

A que se debe este error?

**Comment by csadam** [comment]
Same for me, just installed and
![kep](https://user-images.githubusercontent.com/16628339/39890890-7f93c0d8-549c-11e8-8fd9-9c67a3e3fe75.png)

**Comment by remcovz** [comment]
For me also. On two sites I upgraded tonight I am getting the beforementioned error. On sites I haven't upgraded I don't get the error.

**Comment by ktsaou** [comment]
fixed it!
Sorry for that guys...

**Comment by Anachron** [comment]
I'm still having this issue on

```
 [cron.world] /etc/nginx # netdata -v
netdata 1.10.1_rolling
```

**Comment by Anachron** [comment]
I'm still having this issue/error on `netdata 1.10.1_rolling`.

**Comment by paulfantom** [comment]
@Anachron please upgrade. Current version is 1.11.1.

**Comment by Anachron** [comment]
@paulfantom seems like actually I am at `1.11.0` but it claims to be `netdata 1.10.1_rolling`. 

This is the package template: https://github.com/void-linux/void-packages/blob/a7ada3ea5a55f511dc0fe6ddc22b308f41e0b0b5/srcpkgs/netdata/template#L15

I think the error should not occur in this version.

**Comment by paulfantom** [comment]
Please verify in version v1.11.1, we had some fixes regarding various parts of netdata in that version.

**Comment by Anachron** [comment]
I'll reevaluate the situation once the package on Void Linux is updated to 1.11.1. For now the setup works,- thanks for your quick replies!

**Comment by phunckster** [comment]
Sadly I followed the Info about a new netdata Version. After update it doesn't work anymore giving the error 'Cannot load required JS library: dashboard_info.js' :(
Everything was fine...sometimes you simply should'nt update. Ok that's also no solution.
Funny, after I uninstalled netdata it still shows the error when I visit the adress. Still active the webthingie
here's a screenshot of the error https://d-tool.sytes.net/netnata-installfail.png
It was installed with kickstart.sh, after unsuccessfull update I uninstalled it and installed it again, but same.
Did this to install 'bash <(curl -Ss https://my-netdata.io/kickstart.sh)'
