### ISSUE TITLE
create rpm file from git sources

### ISSUE THREAD

**Issue by ktsaou** [firehol/netdata#678]
A few users ask for instructions on how an RPM file can be created on fedora / rhel / centos, using the git sources.

I tried to use `rpbuild`, but I don't really have it.

@philwhineray @alonbl do you know?

cc: #659

**Comment by alonbl** [comment]
Well, you committed spec changes that I did not agree upon so you are own your own if there are issues within spec, however, the basic principal is:
```
git clone x
cd x
autoreconf -ivf
./configure && make dist
rpmbuild -ts *.gz
yum-builddep *.srpm
rpmbuild --rebuild *.srpm
```

**Comment by philwhineray** [comment]
I am no expert but I gave it a go (on Debian, mind) and hit the following issues:

The Release line appears to assume a packaged version. We can work around this by editing the value:

~~~~
./configure && sed -i -e '/Release/s/%.*/master/' netdata.spec && make dist
~~~~

There is probably a proper way to do this in the actual spec...

Then there appears to be an issue in the `%install` section, introduced in commit 1abb8faa8cba373a530993fea982c92eaf9f176f or maybe it is  when more files are added that match the pattern like in commit aded74ca6acac3f194c9d7e9b0231123dbb91d22

**Comment by alonbl** [comment]
It should work out of the box per my instructions without touching spec file, if you need to touch spec file then someone committed bad code into it. Please fix.

**Comment by ktsaou** [comment]
I walked through all the commits of the spec file: https://github.com/firehol/netdata/commits/master/netdata.spec.in

The only one that can be questionable (I am not an expert though) is this one made by @glensc : https://github.com/firehol/netdata/commit/3fea7af57c42b8df85aef0b6a1e2c56b3c39470e

@alonbl, I am very sorry for this, but I did ask, you had reviewed it and I thought this is it.
Check the PR here: https://github.com/firehol/netdata/pull/186#issuecomment-210009008

Anyway, can we fix it now?

**Comment by alonbl** [comment]
I have no access to rpm based machine right now.
BTW: Who added maintainer mode to autoconf and why?

The tarball should be netdata-1.2.1_master.tar.xz, the spec should take this tarball.
The rpm should be netdata-1.2.1-0.0.master notice that master is going into the release.
There should be no reason to play with the release to make it work, I also don't see where it is being used in spec other than just setting up the release.
If you can send me the build log I will probably be able to help.

**Comment by glensc** [comment]
https://github.com/firehol/netdata/issues/678#issuecomment-232160837 
come on, be specific! you pasted link to whole commit, line numbers please!

**Comment by glensc** [comment]
@alonbl maintainer mode i believe is useful. if you do continuous development on source tree, it should pick up changes to modified files properly (make dependencies) and i do not think am maintainer mode is an issue.

what is the issue anyway i do not get

**Comment by ktsaou** [comment]
> come on, be specific! you pasted link to whole commit, line numbers please!

Don't be offended. @alonbl who initially wrote that file implied that the file is now wrong. As I said I am not an expert. This is just the only commit that affected a lot of the spec file and to my knowledge could possibly break something. All the other commits of this file are very simple (for me).

Check #659 too.

**Comment by ktsaou** [comment]
And @glensc I don't imply I don't want PRs. The opposite. This is a community driven project and I thank all contributors. I am actually very proud this project gets so much attention and I thank you and all the others (e.g. @simonnagl, @paulfantom, the many people that worked on debian packaging, dockerizing, etc) for your contributions.

So, don't be offended. This is not my intention.

**Comment by alonbl** [comment]
@ktsaou, please remove me from these loops. It is obvious that you take advises of less experience people which is completely fine, I have no interest of fight, all I wanted is to help you reach a sane base as we worked out the firehol iprange and build changes.

For maintainer mode see examples such as[1][2][3].
"""Jim Meyering, the inventor of the AM_MAINTAINER_MODE macro was swayed by François’s arguments, and got rid of AM_MAINTAINER_MODE in all of his packages. """

[1] https://blogs.gnome.org/desrt/2011/09/08/am_maintainer_mode-is-not-cool/
[2] https://blog.flameeyes.eu/2008/06/maintaner-mode
[3] https://www.gnu.org/software/automake/manual/html_node/maintainer_002dmode.html

**Comment by glensc** [comment]
i tried to do `rpmbuild -ta`, but it fails with several errors:

preface:
- git fetch upstream && git checkout master 
- i'm at cc26053
- ./autogen.sh && ./configure

first problem:
- `@PACKAGE_RPM_RELEASE@` is expanded empty:
- `%{?release_suffix}` is nowhere defined, don't know what it is, but it was there before my changes. likely for custom release suffixes. can be left as is.
- `%{?dist}` is empty on my system
```
$ grep Release: netdata.spec{,.in}
netdata.spec:Release:   %{?release_suffix}%{?dist}
netdata.spec.in:Release:        @PACKAGE_RPM_RELEASE@%{?release_suffix}%{?dist}
```

these three together produce invalid spec with empty "Release" tag

second problem:
- the source0 url is invalid

the line
`Source0:    http://firehol.org/download/netdata/releases/v@PACKAGE_VERSION@/%{name}-@PACKAGE_VERSION@.tar.xz`

expands to 
`Source0:    http://firehol.org/download/netdata/releases/v1.2.1_master/%{name}-1.2.1_master.tar.xz`

but it should be: `http://firehol.org/download/netdata/releases/master/%{name}-1.2.1_master.tar.xz`

to be able to download such url. it's important just to have `http://firehol.org/download/netdata/releases/master` the rest of the url is irrelevant, github will give the tarball

i'm not able to solve those issues altho they seem trivial, as i'm travelling and be back in a week or two.

for the first problem expand `@PACKAGE_RPM_RELEASE@` as `0.master` for non-release builds, and as `1` for release builds (built from exact tag). this should be done in `configure.ac`. @alonbl already pointed this out

for the second problem i suggest replacing `v@PACKAGE_VERSION@` in the `Source0` line with new macro, which you control similarily, `v1.2.1` for tagged builds and `master` for anything else

**Comment by ktsaou** [comment]
@alonbl please cool down. We have a technical problem here, not a personal one.

I do trust you are going to do whatever is best for the project. We may disagree on certain areas, but this is not necessarily bad. Your work with firehol is exceptional, I am very happy this it and would like you to stay in the loop.

The current situation with netdata is that distribution packages exist only for Arch and Gentoo. I really expected that packages should exist for most distributions by now.

I need to find a way to ease installation for most users. A lot of users ask for pre-build packages. I tried OBS but... ok, this is too much for me... I have spent 2 days trying to make it work for netdata, without success. It requires a lot of background info I don't have. Other users are asking PPAs, etc.

I don't know what to do and I need your help. As the project matures and more modules are added to it (check the excellent work done by @paulfantom on porting all BASH plugins to python), installation gets increasingly complicated. @alonbl I know you will disagree with it, but I needed a way to find all the required packages for each distro. So another installer script has been born: https://github.com/firehol/netdata-demo-site/blob/master/install-required-packages.sh

Check this:

```sh
declare -A pkg_python_mysqldb=(
	   ['arch']="mysql-python"
	 ['centos']="MySQL-python"
	 ['debian']="python-mysqldb"
	 ['gentoo']="dev-python/mysqlclient"
	   ['rhel']="python-mysql"
	   ['suse']="python-MySQL-python"
	['default']="python-mysql"
	)
```

I call it the **hall of shame** of Linux distributions.

I have to admit that until distributions decide to package netdata, probably the simpler solution might be to distribute pre-build tar.gz files that should be untared in `/opt/netdata` with everything installed. Of course I am resisting to the idea, but do feel hopeless...

So, if you can help, please do so...

**Comment by paulfantom** [comment]
@ktsaou not all yet, but I am close. Don't bother with OBS, I will take care of it (or some other automated build system) when I find some time. 

@glensc I have tested #679 on fedora 24. It gives errors about python config files not packaged.

@alonbl please don't walk away.

**Comment by glensc** [comment]
@ktsaou i recently came across http://appimage.org/ but i think it's more desktop oriented

also share your obs pain, i can try help when i'm back in two weeks
also i'm thinking of submitting PR that travis builds rpm. (at least for testing without distributing for starters)

**Comment by danfinn** [comment]
I followed the steps above that @alonbl gave but ran into an error when running yum-builddep.  It appears to be looking for a package that doesn't exist, at least not in the default repos of a fresh CentOS 6.8 install:

```Error: No Package found for libnetfilter_acct-devel```

**Comment by ktsaou** [comment]
Unfortunately, I don't know how to help you. Anyone?

**Comment by glensc** [comment]
the `libnetfilter_acct-devel` error can be probably solved with `--without nfacc`. probably the platform condition to enable nfacct should be updated.

@ktsaou or turn `nfacct` bcond off by default for all platforms?

**Comment by ktsaou** [comment]
> or turn nfacct bcond off by default for all platforms?

yes please.

**Comment by danfinn** [comment]
I found this via google:

https://github.com/firehol/netdata/pull/99/files

I removed the references to libnetfilter from netdata.spec.in and that helped me get further along.  However it's still failing at the final step, when running rpmbuild --rebuild and still complaining about libnetfilter missing so something else must be requiring it.

 
![screen shot 2016-07-25 at 11 58 00 am](https://cloud.githubusercontent.com/assets/5891946/17111495/14ee4618-525f-11e6-84de-93f7580aeddc.png)

**Comment by jasonwbarnett** [comment]
Goal: Easily package and distribute Netdata in a RPM.

I am in dire need of this professionally and am verbally committing to helping getting this done over the next week or so (as time permits).

**Comment by danfinn** [comment]
I am in a similar situation (although I'd use a different word than "dire") and I'm willing to help out as much as possible although my skills on this are limited.

I have a good size environment that I'd love to roll out netdata to but I can't easily automate that in it's current state.  What I really need is a package for both CentOS and Ubuntu.

I went back through and removed every reference to libnetfilter and nfacct from the netdata.spec.in file and that got further along the build process but it then error'd out on a missing python.d directory.

It sounds like at one point there was a working spec file.  Any chance we could get that back?
