### ISSUE TITLE
Error 405: Cannot download charts index from server

### ISSUE THREAD

**Issue by casperklein** [firehol/netdata#715]
Version: 1fb6da8a7c81509d36cd399bb0cb2d453ad233b6 

As mentioned in https://github.com/firehol/netdata/issues/347, I checked the generated JSON.

Referring to jsonlint.com, the line:

> "family": "/a/b/c/Foo\040Bar",

causes the problem.

```
		"disk_svctm.dm-2": {
			"id": "disk_svctm.dm-2",
			"name": "disk_svctm.dm_2",
			"type": "disk_svctm",
			"family": "/a/b/c/Foo\040Bar",
			"context": "disk.svctm",
			"title": "Average Service Time (disk_svctm.dm_2)",
			"priority": 2007,
			"enabled": true,
			"units": "ms per operation",
			"data_url": "/api/v1/data?chart=disk_svctm.dm_2",
			"chart_type": "line",
			"duration": 3600,
			"first_entry": 1469044546,
			"last_entry": 1469044832,
			"update_every": 1,
			"dimensions": {
				"svctm": {
					"name": "svctm"
				}
			}
		},
```

fyi: It's a directory containing a space in it's name, which I mount a file system to.

If I should provide further information, let me know.

**Comment by ktsaou** [comment]
What bothers be is `\040`. I don't convert spaces. Where did it came from?

I see in the code this string is copied from `/proc/self/mountinfo`. Can you post this file?

**Comment by ktsaou** [comment]
Also, can you find the chart configuration in `http://your.netdata:19999/netdata.conf`?

**Comment by casperklein** [comment]
```
[plugin:cgroups]
	# cgroups plugin resources = yes
	# check for new cgroups every = 10
	# enable cpuacct stat = auto
	# enable cpuacct usage = auto
	# enable memory = auto
	# enable blkio = auto
	# path to /sys/fs/cgroup/cpuacct = /sys/fs/cgroup/cpuacct
	# path to /sys/fs/cgroup/blkio = /sys/fs/cgroup/blkio
	# path to /sys/fs/cgroup/memory = /sys/fs/cgroup/memory
	# path to /sys/fs/cgroup/devices = /sys/fs/cgroup/devices
	# max cgroups to allow = 500
	# max cgroups depth to monitor = 0
	# enable new cgroups detected at run time = yes
```

**Comment by ktsaou** [comment]
It is not that.
Search for section `disk_svctm.dm-2`.

Also post your `/proc/self/mountinfo` please.

**Comment by casperklein** [comment]
Mountinfo:

 ```
14 20 0:13 / /sys rw,nosuid,nodev,noexec,relatime - sysfs sysfs rw
15 20 0:3 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
16 20 0:5 / /dev rw,relatime - devtmpfs udev rw,size=10240k,nr_inodes=124561,mode=755
17 16 0:10 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,gid=5,mode=620,ptmxmode=000
18 20 0:14 / /run rw,nosuid,noexec,relatime - tmpfs tmpfs rw,size=100960k,mode=755
20 1 9:1 / / rw,relatime - ext3 /dev/md1 rw,errors=continue,barrier=1,data=ordered
21 18 0:16 / /run/lock rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=5120k
22 18 0:17 / /run/shm rw,nosuid,nodev,noexec,relatime - tmpfs tmpfs rw,size=622800k
23 20 9:0 / /boot rw,nosuid,nodev,relatime - ext2 /dev/md0 rw,errors=continue
24 14 0:18 / /sys/fs/fuse/connections rw,relatime - fusectl fusectl rw
25 20 0:19 / /tmp/.truecrypt_aux_mnt1 rw,nosuid,nodev,relatime - fuse.truecrypt truecrypt rw,user_id=0,group_id=0,allow_other
26 20 253:0 / /x/y rw,relatime - ext3 /dev/mapper/truecrypt1 rw,errors=continue,barrier=1,data=ordered
27 20 0:20 / /tmp/.truecrypt_aux_mnt2 rw,nosuid,nodev,relatime - fuse.truecrypt truecrypt rw,user_id=0,group_id=0,allow_other
28 20 253:1 / /q/w rw,relatime - ext3 /dev/mapper/truecrypt2 rw,errors=continue,user_xattr,acl,barrier=1,data=ordered
29 20 0:21 / /tmp/.truecrypt_aux_mnt3 rw,nosuid,nodev,relatime - fuse.truecrypt truecrypt rw,user_id=0,group_id=0,allow_other
30 26 253:2 / /a/b/c/Foo\040Bar rw,relatime - ext3 /dev/mapper/truecrypt3 rw,errors=continue,user_xattr,acl,barrier=1,data=ordered
```

**Comment by ktsaou** [comment]
hmm... I see, the kernel does this...

let me check for a solution...

**Comment by casperklein** [comment]
```
[disk_svctm.dm-2]
	# history = 3600
	# enabled = yes
	# cache directory = /netdata/var/cache/netdata/disk_svctm.dm_2
	# chart type = line
	# type = disk_svctm
	# family = /a/b/c/Foo\040Bar
	# context = disk.svctm
	# units = ms per operation
	# priority = 2007
	# gap when lost iterations above = 1
	# name = disk_svctm.dm_2
	# title = Average Service Time (disk_svctm.dm_2)
	# dim svctm name = svctm
	# dim svctm algorithm = absolute
	# dim svctm multiplier = 1
	# dim svctm divisor = 1
```

**Comment by ktsaou** [comment]
thanks! I am coding a fix...

**Comment by ktsaou** [comment]
I have fixed it in my private repo. Could you please test it before merging it?

Run `git clone https://github.com/ktsaou/netdata.git netdata-ktsaou.git` and install this version (the directory will be named `netdata-ktsaou.git`.

If it works, I'll merge it to the main repo.

**Comment by casperklein** [comment]
Not fixed for me. Same error.

Version is: ffe486a2093c29f54dd3113f99cdfcb2c08d952d

**Comment by ktsaou** [comment]
thanks! my bad (what was I thinking?)

Could you please try again. It should work now (I emulated it and verified it does, but let's check it live).

Thanks!

**Comment by casperklein** [comment]
Fixed! Thank you for your ultra fast support :+1:
